/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Submission_Java;

/**
 *
 * @author User
 */
public class STMIK_Library extends javax.swing.JFrame {

    /**
     * Creates new form STMIK_Library
     */
    public STMIK_Library() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkodepeminjam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnamapeminjam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttarif = new javax.swing.JLabel();
        txtjudulbuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPotongan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnprosestotal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnprosesbuku = new javax.swing.JButton();
        txtTarif = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtkodebuku = new javax.swing.JTextField();
        txttarif1 = new javax.swing.JLabel();
        txtDurasi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Peminjam          : ");

        txtkodepeminjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Peminjam     : ");

        txtnamapeminjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Status                    : ");

        txtstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnproses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtnamapeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(txtkodepeminjam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnproses))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkodepeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamapeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnproses)
                .addGap(7, 7, 7))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Buku              :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Judul Buku              :");

        txttarif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttarif.setText("Tarif Buku/ Hari        :");

        txtjudulbuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Potongan/Cashback :");

        txtPotongan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPotongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPotonganActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total                       :");

        btnprosestotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnprosestotal.setText("Proses Total");
        btnprosestotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosestotalActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkeluar.setText("Keluar ");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnprosesbuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnprosesbuku.setText("Proses");
        btnprosesbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesbukuActionPerformed(evt);
            }
        });

        txtTarif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtkodebuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txttarif1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttarif1.setText("Durasi Pinjam          :");

        txtDurasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txttarif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txttarif1))
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPotongan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(txtDurasi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTarif, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjudulbuku, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkodebuku, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprosestotal)
                    .addComponent(btnprosesbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprosesbuku))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttarif)
                            .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttarif1)
                            .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkeluar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnhapus)
                        .addGap(98, 98, 98)
                        .addComponent(btnprosestotal)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setForeground(new java.awt.Color(240, 240, 240));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STMIK-MJ Library Official");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        
        // 1.Deklarasi Variable yang terdapat pada ID Peminjam, Status , Kode Buku 
        // Menggunakan tipe data String untuk pemprosesan lebih lanjut 
        String kodepeminjam,Status,nama;
        
        // Kode Buku dideklarasikan dalam bentuk string dari sebuah penginputan pada kode peminjam maka akan menghasilkan sebuah text.
        kodepeminjam = String.valueOf(txtkodepeminjam.getText());
        
        // Apabila di process menggunakan Huruf no Kapital : a001 maka output nya akan menghasilkan result : tidak terdaftar
        // Apabila di process menggunakan Huruf Kapital : A001 maka output nya akan menghasilkan result : Anggota 
        // setelah memasukan sebuah if condition jangan lupa memberikan input OR  (||)  
        //  apabila kita di minta untuk memilih pilihan benar maka kita menggunakan fungsi OR 
        if (kodepeminjam.equals("A001") ||   kodepeminjam.equals("a001")) {
            Status = "Members";
        }else 
            if (kodepeminjam.equals("B002") ||   kodepeminjam.equals("b002")) {
            Status = "Non Member";
        }else 
               if (kodepeminjam.equals("C003") ||   kodepeminjam.equals("c003")) {
            Status = "Staff";
        }else 
               if (kodepeminjam.equals("D005") ||   kodepeminjam.equals("d005")) {
            Status = "Dosen";
        }else 
             if (kodepeminjam.equals("E005") ||   kodepeminjam.equals("e005")) {
            Status = "Visitor";
        }else        
        {
                Status = "User Not Found, Please check again!";
        }
            txtstatus.setText(""+ Status);
        
    }//GEN-LAST:event_btnprosesActionPerformed

    private void btnprosesbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesbukuActionPerformed
        // TODO add your handling code here:
        
        // Deklarasi Variable
        String judulbuku;
        int KodeBuku;
        double Tarif;
        
        KodeBuku = Integer.parseInt(txtkodebuku.getText());
        
        if (KodeBuku ==1111) {
            judulbuku = "Bahasa Pemograman Java";
            Tarif = 15000;
        }else
            
            if (KodeBuku ==2222 ) {
            judulbuku = "Sistem Berkas";
            Tarif = 20000;
        }else
                
          if (KodeBuku ==3333 ) {
            judulbuku = "Data Mining";
            Tarif = 25000;
        }else
                                    
                if (KodeBuku ==4444 ) {
            judulbuku = "Responsi Al-Qur'an AL -ISLAM";
            Tarif = 30000;
        }else
                    
            if (KodeBuku ==5555 ) {
            judulbuku = "Alam Pikiran Muhammadiyah";
            Tarif = 27500;
        }else
                                
           if (KodeBuku ==6666 ) {
            judulbuku = "Framework Java Springboot";
            Tarif = 22500;
        }else
               
            if (KodeBuku == 7777 ) {
            judulbuku = "Memulai Pemograman Kotlin";
            Tarif = 25000;
        }else
                
            if (KodeBuku == 8888 ) {
            judulbuku = "Cloud & Big Data";
            Tarif = 18000;
        }else
                                            
            if (KodeBuku == 9999 ) {
            judulbuku = "Bahasa Pemograman R";
            Tarif = 23000;
        }else
                                                
              if (KodeBuku ==1212 ) {
            judulbuku = "Sistem Jaringan Komputer ";
            Tarif = 18000;
        }else                                          
              
         if (KodeBuku == 1313 ) {
            judulbuku = "Analisis Jaringan Komputer ";
            Tarif = 18000;
        }else      
             
        if (KodeBuku == 1414 ) {
            judulbuku = "Jaringan Komputer di Windows dan Linux";
            Tarif = 14000;
        }else      
            
       if (KodeBuku == 1515) {
            judulbuku = "Algoritma Pemograman  ";
            Tarif = 26000;
        }else      
             
        if (KodeBuku == 1616) {
            judulbuku = "Visual Basic 6 ";
            Tarif = 32000;
        }else    
            
        if (KodeBuku == 0015) {
            judulbuku = "Pemograman Android  ";
            Tarif = 40000;
        }else     
            
       if (KodeBuku == 1717) {
            judulbuku = "Tilawah Ibadah Kitabah  ";
            Tarif = 14000;
        }else      
           
        if (KodeBuku == 1818 ) {
            judulbuku = "Pemograman Web PHP ";
            Tarif = 23000;
        }else    
            
        if (KodeBuku == 1919) {
            judulbuku = "Aplikasi Pemograman dengan PHP dan MySQL ";
            Tarif = 17000;
        }else     
            
          if (KodeBuku ==  2020) {
            judulbuku = "Muhammadiyah Abad Kedua";
            Tarif = 40000;
        }else   
              
          if (KodeBuku ==2121) {
            judulbuku = "Ideologi Muhammadiyah ";
            Tarif = 36000;
        }else     
              
          if (KodeBuku == 2323) {
            judulbuku = "Muhammadiyah Gerakan Kebudayaan yang berkemajuan ";
            Tarif = 35000;
        }else     
              
        if (KodeBuku ==2424) {
            judulbuku = "Muhammadiyah Sebagai Gerakan Islam ";
            Tarif = 23000;
        }else       
            
         if (KodeBuku ==2525 ) {
            judulbuku = "Etika Muhammadiyah & Spirit Peradaban ";
            Tarif = 37000;
        }else    
             
         if (KodeBuku ==2626 ) {
            judulbuku = "The Power of Digital Marketing  ";
            Tarif = 27000;
        }else     
             
          if (KodeBuku == 2727) {
            judulbuku = "The Fundamental of Digital Marketing";
            Tarif = 25000;
        }else     
      if (KodeBuku ==2828 ) {
            judulbuku = "Digital Marketing dan Fintech ";
            Tarif = 18000;
        }else       
        if (KodeBuku ==2929) {
            judulbuku = "The Fundamental of Digital Marketing";
            Tarif = 25000;
        }else   
       if (KodeBuku ==3030) {
            judulbuku = "Digital Branding Concept & Practice ";
            Tarif = 21000;
        }else      
      if (KodeBuku ==3131) {
            judulbuku = "Internet Marketing for Your Business  ";
            Tarif = 26900;
        }else            
      {
          // Jika Judul Buku diluar List Maka akan menampilkan notifikasi : Not Found Book !
          judulbuku = "Not Found Book!";
          Tarif      = 0;
      }
                txtjudulbuku.setText(""+judulbuku);
                txtTarif.setText("" + Tarif);
               
    }//GEN-LAST:event_btnprosesbukuActionPerformed

    private void txtPotonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPotonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPotonganActionPerformed

    private void btnprosestotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosestotalActionPerformed
        // TODO add your handling code here:
        
        // Deklarasi Variable 
        String status;
        double Tarif,Total,Potongan;
          int Durasi;
          
          status  = String.valueOf(txtstatus.getText());
          Durasi = Integer.parseInt(txtDurasi.getText());
          Tarif = Double.parseDouble(txtTarif.getText());
          
          if (Durasi >= 10 &&  status.equals("Members")) {
                 Potongan = 0.1 * Tarif;
          } else
          if (Durasi >= 10 && status.equals("Dosen")) {
                  Potongan = 0.2 * Tarif;
                  }else{
               Potongan = 0;
                  }
           txtPotongan.setText(""+ Potongan);
           
             Total = (Durasi * Tarif) - Potongan;
             txttotal.setText(""+Total);
    }//GEN-LAST:event_btnprosestotalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        // Code untuk button exit 
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        txtkodepeminjam.setText("");
        txtnamapeminjam.setText("");
        txtstatus.setText("");
        txtkodebuku.setText("");
        txtkodebuku.setText("");
        txtTarif.setText("");
        txtDurasi.setText("");
        txtPotongan.setText("");
        txttotal.setText("");
        //Membuat cursor kembali kepada field kode peminjam apabila setelah fungsi dijalankan ( done proses ) 
        txtkodepeminjam.requestFocus();
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STMIK_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STMIK_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STMIK_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STMIK_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STMIK_Library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnproses;
    private javax.swing.JButton btnprosesbuku;
    private javax.swing.JButton btnprosestotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtPotongan;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtjudulbuku;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtkodepeminjam;
    private javax.swing.JTextField txtnamapeminjam;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JLabel txttarif;
    private javax.swing.JLabel txttarif1;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
